apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgresns
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007  # NodePort must be in the range 30000-32767
  selector:
    app: postgres
